version: 2.1
orbs:
  node: circleci/node@1.1.6-browsers
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm ci
            - run: npm run build
            - run: npm test
workflows:
    build:
      jobs:
        - build-and-test