version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.15-browsers
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache: # special step to restore the dependency cache
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install
          command: npm ci
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: build
          command: npm run build
      - run:
          name: test
          command: npm run test:ci
  build-and-deploy-demo:
    docker:
      - image: circleci/node:12:15
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - 'f8:9e:98:05:cd:42:be:49:33:75:bc:9d:88:36:ab:9e'
      - run:
          name: install
          command: npm ci
      - run:
          name: build-demo
          command: npm run build:demo
      - run:
          name: commit
          command: git commit -am 'Docs generated [ci skip]'
      - run:
          name: push
          command: git push
workflows:
  build:
    jobs:
      - build
      - build-and-deploy-demo
